name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - README.md
      - docs/**

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    # objc2を利用しているため、macOSで実行する必要がある
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Check clippy
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test
